"""init base tables

Revision ID: 5842f5236297
Revises: 
Create Date: 2026-07-07 01:05:14.616000
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5842f5236297'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_code'), 'role', ['code'], unique=True)
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('avatar', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('real_name_status', sa.String(length=32), nullable=False),
    sa.Column('is_guest', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    op.create_table('file_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('public_url', sa.String(length=512), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['uploader_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_asset_id'), 'file_asset', ['id'], unique=False)
    op.create_index(op.f('ix_file_asset_uploader_id'), 'file_asset', ['uploader_id'], unique=False)
    op.create_table('operation_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('operator_type', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('before_data', sa.Text(), nullable=True),
    sa.Column('after_data', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_log_action'), 'operation_log', ['action'], unique=False)
    op.create_index(op.f('ix_operation_log_id'), 'operation_log', ['id'], unique=False)
    op.create_index(op.f('ix_operation_log_operator_id'), 'operation_log', ['operator_id'], unique=False)
    op.create_index(op.f('ix_operation_log_request_id'), 'operation_log', ['request_id'], unique=False)
    op.create_index(op.f('ix_operation_log_target_id'), 'operation_log', ['target_id'], unique=False)
    op.create_index(op.f('ix_operation_log_target_type'), 'operation_log', ['target_type'], unique=False)
    op.create_table('pet_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('breed', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('arrival_date', sa.Date(), nullable=True),
    sa.Column('weight', sa.String(length=32), nullable=True),
    sa.Column('avatar', sa.String(length=512), nullable=True),
    sa.Column('sterilized', sa.String(length=16), nullable=False),
    sa.Column('vaccine_status', sa.String(length=32), nullable=False),
    sa.Column('deworm_status', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pet_profile_id'), 'pet_profile', ['id'], unique=False)
    op.create_index(op.f('ix_pet_profile_type'), 'pet_profile', ['type'], unique=False)
    op.create_index(op.f('ix_pet_profile_user_id'), 'pet_profile', ['user_id'], unique=False)
    op.create_table('real_name_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('real_name', sa.String(length=128), nullable=False),
    sa.Column('id_card_no', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('audit_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_real_name_auth_id'), 'real_name_auth', ['id'], unique=False)
    op.create_index(op.f('ix_real_name_auth_user_id'), 'real_name_auth', ['user_id'], unique=False)
    op.create_table('user_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('receiver_name', sa.String(length=64), nullable=False),
    sa.Column('receiver_phone', sa.String(length=32), nullable=False),
    sa.Column('province', sa.String(length=64), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('district', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.String(length=255), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_address_id'), 'user_address', ['id'], unique=False)
    op.create_index(op.f('ix_user_address_user_id'), 'user_address', ['user_id'], unique=False)
    op.create_table('user_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('auth_type', sa.String(length=32), nullable=False),
    sa.Column('identifier', sa.String(length=128), nullable=False),
    sa.Column('credential', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_type', 'identifier', name='uq_auth_type_identifier')
    )
    op.create_index(op.f('ix_user_auth_auth_type'), 'user_auth', ['auth_type'], unique=False)
    op.create_index(op.f('ix_user_auth_id'), 'user_auth', ['id'], unique=False)
    op.create_index(op.f('ix_user_auth_identifier'), 'user_auth', ['identifier'], unique=False)
    op.create_index(op.f('ix_user_auth_user_id'), 'user_auth', ['user_id'], unique=False)
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('signature', sa.String(length=255), nullable=True),
    sa.Column('has_pet', sa.Boolean(), nullable=False),
    sa.Column('interest_tags', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profile_id'), 'user_profile', ['id'], unique=False)
    op.create_index(op.f('ix_user_profile_user_id'), 'user_profile', ['user_id'], unique=True)
    op.create_table('user_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    op.create_index(op.f('ix_user_role_id'), 'user_role', ['id'], unique=False)
    op.create_index(op.f('ix_user_role_role_id'), 'user_role', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_role_user_id'), 'user_role', ['user_id'], unique=False)
    op.create_table('pet_growth_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('media_asset_ids', sa.String(length=512), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pet_profile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pet_growth_record_id'), 'pet_growth_record', ['id'], unique=False)
    op.create_index(op.f('ix_pet_growth_record_pet_id'), 'pet_growth_record', ['pet_id'], unique=False)
    op.create_index(op.f('ix_pet_growth_record_record_type'), 'pet_growth_record', ['record_type'], unique=False)
    op.create_index(op.f('ix_pet_growth_record_user_id'), 'pet_growth_record', ['user_id'], unique=False)
    op.create_table('pet_health_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.String(length=32), nullable=False),
    sa.Column('hospital', sa.String(length=128), nullable=True),
    sa.Column('doctor', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pet_profile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pet_health_record_id'), 'pet_health_record', ['id'], unique=False)
    op.create_index(op.f('ix_pet_health_record_pet_id'), 'pet_health_record', ['pet_id'], unique=False)
    op.create_index(op.f('ix_pet_health_record_record_type'), 'pet_health_record', ['record_type'], unique=False)
    op.create_index(op.f('ix_pet_health_record_user_id'), 'pet_health_record', ['user_id'], unique=False)
    op.create_table('pet_reminder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.Column('reminder_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('remind_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pet_profile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pet_reminder_id'), 'pet_reminder', ['id'], unique=False)
    op.create_index(op.f('ix_pet_reminder_pet_id'), 'pet_reminder', ['pet_id'], unique=False)
    op.create_index(op.f('ix_pet_reminder_remind_at'), 'pet_reminder', ['remind_at'], unique=False)
    op.create_index(op.f('ix_pet_reminder_reminder_type'), 'pet_reminder', ['reminder_type'], unique=False)
    op.create_index(op.f('ix_pet_reminder_user_id'), 'pet_reminder', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pet_reminder_user_id'), table_name='pet_reminder')
    op.drop_index(op.f('ix_pet_reminder_reminder_type'), table_name='pet_reminder')
    op.drop_index(op.f('ix_pet_reminder_remind_at'), table_name='pet_reminder')
    op.drop_index(op.f('ix_pet_reminder_pet_id'), table_name='pet_reminder')
    op.drop_index(op.f('ix_pet_reminder_id'), table_name='pet_reminder')
    op.drop_table('pet_reminder')
    op.drop_index(op.f('ix_pet_health_record_user_id'), table_name='pet_health_record')
    op.drop_index(op.f('ix_pet_health_record_record_type'), table_name='pet_health_record')
    op.drop_index(op.f('ix_pet_health_record_pet_id'), table_name='pet_health_record')
    op.drop_index(op.f('ix_pet_health_record_id'), table_name='pet_health_record')
    op.drop_table('pet_health_record')
    op.drop_index(op.f('ix_pet_growth_record_user_id'), table_name='pet_growth_record')
    op.drop_index(op.f('ix_pet_growth_record_record_type'), table_name='pet_growth_record')
    op.drop_index(op.f('ix_pet_growth_record_pet_id'), table_name='pet_growth_record')
    op.drop_index(op.f('ix_pet_growth_record_id'), table_name='pet_growth_record')
    op.drop_table('pet_growth_record')
    op.drop_index(op.f('ix_user_role_user_id'), table_name='user_role')
    op.drop_index(op.f('ix_user_role_role_id'), table_name='user_role')
    op.drop_index(op.f('ix_user_role_id'), table_name='user_role')
    op.drop_table('user_role')
    op.drop_index(op.f('ix_user_profile_user_id'), table_name='user_profile')
    op.drop_index(op.f('ix_user_profile_id'), table_name='user_profile')
    op.drop_table('user_profile')
    op.drop_index(op.f('ix_user_auth_user_id'), table_name='user_auth')
    op.drop_index(op.f('ix_user_auth_identifier'), table_name='user_auth')
    op.drop_index(op.f('ix_user_auth_id'), table_name='user_auth')
    op.drop_index(op.f('ix_user_auth_auth_type'), table_name='user_auth')
    op.drop_table('user_auth')
    op.drop_index(op.f('ix_user_address_user_id'), table_name='user_address')
    op.drop_index(op.f('ix_user_address_id'), table_name='user_address')
    op.drop_table('user_address')
    op.drop_index(op.f('ix_real_name_auth_user_id'), table_name='real_name_auth')
    op.drop_index(op.f('ix_real_name_auth_id'), table_name='real_name_auth')
    op.drop_table('real_name_auth')
    op.drop_index(op.f('ix_pet_profile_user_id'), table_name='pet_profile')
    op.drop_index(op.f('ix_pet_profile_type'), table_name='pet_profile')
    op.drop_index(op.f('ix_pet_profile_id'), table_name='pet_profile')
    op.drop_table('pet_profile')
    op.drop_index(op.f('ix_operation_log_target_type'), table_name='operation_log')
    op.drop_index(op.f('ix_operation_log_target_id'), table_name='operation_log')
    op.drop_index(op.f('ix_operation_log_request_id'), table_name='operation_log')
    op.drop_index(op.f('ix_operation_log_operator_id'), table_name='operation_log')
    op.drop_index(op.f('ix_operation_log_id'), table_name='operation_log')
    op.drop_index(op.f('ix_operation_log_action'), table_name='operation_log')
    op.drop_table('operation_log')
    op.drop_index(op.f('ix_file_asset_uploader_id'), table_name='file_asset')
    op.drop_index(op.f('ix_file_asset_id'), table_name='file_asset')
    op.drop_table('file_asset')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_index(op.f('ix_role_code'), table_name='role')
    op.drop_table('role')
    # ### end Alembic commands ###
